# Generated by Django 3.0.14 on 2023-03-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animal', models.CharField(max_length=100)),
                ('tipo_animal', models.CharField(max_length=80)),
                ('edad_animal', models.CharField(max_length=15)),
                ('precio_tratamiento', models.FloatField()),
                ('pre_diagnostico', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menues')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
